# Generated by Django 5.1.3 on 2025-04-13 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesureRefroidisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('debit_farine', models.FloatField()),
                ('commentaires', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grate', models.CharField(max_length=100)),
                ('chambre', models.CharField(max_length=20)),
                ('fan', models.CharField(max_length=100)),
                ('flow', models.FloatField()),
                ('flow_specifique', models.FloatField()),
                ('area', models.FloatField()),
                ('sp_air_load', models.FloatField()),
                ('sp_air_load_kg', models.FloatField()),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='refroidisseur_app.mesurerefroidisseur')),
            ],
        ),
        migrations.CreateModel(
            name='VentilateurMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('debit', models.FloatField()),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventilateurs', to='refroidisseur_app.mesurerefroidisseur')),
            ],
        ),
    ]
