# Generated by Django 5.1.3 on 2025-04-13 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refroidisseur_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mesure_images/')),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='refroidisseur_app.mesurerefroidisseur')),
            ],
        ),
    ]
